import { Theme, Container } from "@radix-ui/themes";
import "@radix-ui/themes/layout.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import { ThemeProvider } from "next-themes";
import { GlobalNavigation } from "./_components/GlobalNavigation/index";
import { ThemeToggle } from "./_components/ThemeToggle";
import GlobalPropsProvider from "./_context/global-props";
import { sessionAvailable } from "./actions";
import { graphqlClient, GraphQLProvider } from "../lib/graphql-client";

const headingMono = IBM_Plex_Sans({
  variable: "--font-heading",
  style: "normal",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionCheck = await sessionAvailable();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${headingMono.variable}`}>
        <ThemeProvider attribute="class">
          <GlobalPropsProvider
            globalProps={{
              sessionAvailable: sessionCheck,
            }}
          >
            <GraphQLProvider value={graphqlClient}>
              <Theme
                accentColor="cyan"
                radius="medium"
                scaling="110%"
                hasBackground={false}
              >
                <Container p="6" size="4">
                  <GlobalNavigation />
                  <ThemeToggle className={styles.ThemeToggleButton} />
                  <main>
                    <Container p="6">{children}</Container>
                  </main>
                </Container>
              </Theme>
            </GraphQLProvider>
          </GlobalPropsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
